namespace CodeNames
{
    public enum GameState
    {
        NULL,

        INIT,
        INIT_DONE,
        PICK_TEAMS,
        PICK_TEAMS_DONE_BLUE_TO_START,
        PICK_TEAMS_DONE_RED_TO_START,
        
        BLUE_TEAM_TURN_CODEMASTER_START,
        BLUE_TEAM_TURN_CODEMASTER_TIMEOUT,
        BLUE_TEAM_TURN_CODEMASTER_SUBMISSION_DONE,
        BLUE_TEAM_TURN_START,
        BLUE_TEAM_TURN_CONTINUE,
        BLUE_TEAM_TURN_TIMEOUT,
        BLUE_TEAM_TURN_END,
        BLUE_TEAM_TURN_SUBMISSION_DONE,
        BLUE_TEAM_WINS,
        
        RED_TEAM_TURN_CODEMASTER_START,
        RED_TEAM_TURN_CODEMASTER_TIMEOUT,
        RED_TEAM_TURN_CODEMASTER_SUBMISSION_DONE,
        RED_TEAM_TURN_START,
        RED_TEAM_TURN_CONTINUE,
        RED_TEAM_TURN_TIMEOUT,
        RED_TEAM_TURN_END,
        RED_TEAM_TURN_SUBMISSION_DONE,
        RED_TEAM_WINS
    }
}
